# Spring DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/agrotrack-suscription-db?useSSL=true&serverTimezone=UTC&createDatabaseIfNotExist=true&publicKeyRetrieval=true
spring.datasource.username=${FLOWEYTECH_DB_USERNAME}
spring.datasource.password=${FLOWEYTECH_DB_USERNAME}